### PR TITLE
WIP: Avoid SA-CONTRIB-2015-052 - RESTful Web Services - Access Bypass

### PR DESCRIPTION
**Pull request by amitaibu**
#413

Currently just a simple copy/ paste form the [original](http://cgit.drupalcode.org/restws/commit/?id=01724e0) restws commit.

### CODE REVIEW

**Comment by amitaibu** [comment]
Actually, our cache layer is completely different. So we should probably just keep the test

**Comment by e0ipso** [comment]
Have you checked `\RestfulManager::pageFooter()`? (talking from memory).

**Comment by amitaibu** [comment]
I'll first try to reproduce the RESTws bug with RESTful, and then we can also add a simpleTest just to be extra sure we won't get the same "cache pollution" issue.

**Comment by amitaibu** [comment]
This PR should probably include only the tests part - so we validate we don't have this cache poisoning.

**Pull request closed without merging**
