### PR TITLE
Add docs about using .htaccess along with basic auth.

### PR DESCRIPTION
**Pull request by amitaibu**

### CODE REVIEW

**Comment by amitaibu** [comment]
@mateu-aguilo-bosch actually a better/another solution would be providing a variable that will skip basic auth authentication. Like this we could keep having `'authentication_types' => TRUE` in the code, by have a variable that will allow enable/ disable between environments.

**Comment by amitaibu** [comment]
@mateu-aguilo-bosch added variable..

**Comment by e0ipso** [comment]
@amitaibu wouldn't this be achieved by not having the authentication provider enabled for the resource?

**Comment by amitaibu** [comment]
This is for a scenario where DEV server is protected by .htaccess, but you want to provide basic auth on the LIVE server.

**Comment by e0ipso** [comment]
Alright then. This looks good.

**Comment by amitaibu** [comment]
Merged.

**Pull request closed without merging**
