### PR TITLE
Map property reference in example module

### PR DESCRIPTION
**Pull request by amitaibu**
Make `resource` more visible, as it's very handy.

### CODE REVIEW

**Comment by e0ipso** [comment]
Very handy indeed. Can we also add a note to our beloved docs too?

Other than that, this is ready to go.

**Comment by amitaibu** [comment]
Yap, that's my plan. Stay tuned :)

**Comment by amitaibu** [comment]
Docs added.

**Comment by amitaibu** [comment]
@mateu-aguilo-bosch ready for review

**Comment by e0ipso** [comment]
Looking good! Merging!

**Comment by e0ipso** [comment]
Merged in https://github.com/Gizra/restful/commit/e28b20041f96e48a9369b360f2efe5e1e72e7175.

**Pull request closed without merging**
