### PR TITLE
Return null for empty or unavailable fields - addresses issue #492

### PR DESCRIPTION
**Pull request by krisgraham**

### CODE REVIEW

**Comment by amitaibu** [comment]
Not sure this approach is right, as if you don't have access to a field, you shouldn't know about it.

**Comment by krisgraham** [comment]
@amitaibu That makes sense, but means you'll probably need a separate if() before the access check to specifically check for empty content. If that sounds alright, I'll create another PR for it.

**Comment by amitaibu** [comment]
If the user has access and the content is empty - we can show the property.

**Comment by e0ipso** [comment]
@krisgraham are you still working on this? May I provide direction?

Thanks.

**Comment by e0ipso** [comment]
I'm going to close this issue to unclutter the PR view. Feel free to re-open if you pick up this work again.

Thanks for everything!

**Pull request closed without merging**
