### PR TITLE
[BUGFIX] Filtering by property should query by its schema field also if the operator is either In or BETWEEN.

### PR DESCRIPTION
**Pull request by ordavidil**
#912

### CODE REVIEW

**Comment by ordavidil** [comment]
@amitaibu 
ready for review

**Comment by amitaibu** [comment]
Any chance for a test?  :)

**Comment by ordavidil** [comment]
@amitaibu 
New test is on :)

**Comment by e0ipso** [comment]
This is great work! Thanks @ordavidil.

**Comment by amitaibu** [comment]
👍

**Pull request merged**
