### PR TITLE
Move cache settings in the plugin under "cache"

### PR DESCRIPTION
**Pull request by e0ipso**
This would be inline with [rate-limit](https://github.com/Gizra/restful/pull/71/files#diff-14193d8819c728c2b3c0981ef73a848eR13)

### CODE REVIEW

**Comment by amitaibu** [comment]
Needs a re-roll :)

**Comment by e0ipso** [comment]
Re rolled-

**Comment by amitaibu** [comment]
Sorry, I think my latest commit broke the re-roll https://github.com/Gizra/restful/pull/71#issuecomment-46953016

**Comment by e0ipso** [comment]
Should be fixed

**Comment by amitaibu** [comment]
Merged, thanks.

**Pull request closed without merging**
