### PR TITLE
Allow referenced resource to show only entity ID(s)

### PR DESCRIPTION
**Pull request by amitaibu**

### CODE REVIEW

**Comment by amitaibu** [comment]
Maybe the default of `full_view` should be FALSE by default?

**Comment by amitaibu** [comment]
@mateu-aguilo-bosch ready for review.

**Comment by e0ipso** [comment]
This is good to be merged.

I think sub-resources need a bit more flexibility since someone could want to have the URI as an identifier instead of the internal Drupal ID. Or even more, we could want to have true HAL support for embedded resources. Let's talk about this somewhere.

Hypertext Application Language

**Comment by e0ipso** [comment]
Merged!

**Pull request closed without merging**
