### PR TITLE
Add utility function to return image URLs based on image styles.

### PR DESCRIPTION
**Pull request by amitaibu**

### CODE REVIEW

**Comment by amitaibu** [comment]
(Still untested)

**Comment by amitaibu** [comment]
Tested, waiting for Travis to come back green

**Comment by e0ipso** [comment]
Can we have tests for this somehow?

**Comment by amitaibu** [comment]
We could probably check that the array returns with some values. I'll try.

**Comment by e0ipso** [comment]
Let me have a go at this. Since most client side technologies have problems resizing the images appropriately, I think this is something restful should deal with by default.

**Comment by amitaibu** [comment]
Closed in favor of #145

**Pull request closed without merging**
