### PR TITLE
Support for field collections

### PR DESCRIPTION
**Pull request by kzoltan**
Based on the #376 issue, the solution suggested by @rivkitzipory

### CODE REVIEW

**Comment by e0ipso** [comment]
This looks good to me.

**Comment by kzoltan** [comment]
Does this mean that its now in there in the dev version of the drupal.org module?
What is your strategy on the releases? When will this be part of a stable release?

Is there somewhere a documentation about this just that I didn't read it?

**Comment by e0ipso** [comment]
Should be there in no time ☺

**Comment by lukewertz** [comment]
It looks like this PR merged some, but not all of the code necessary to support field collections. It looks like @rivkitzipory added a file here: https://github.com/rivkitzipory/restful/commit/96ed9ea0f82505dcb95eeee0016753f5c19fa178

Should that not have been included in the PR?

**Pull request merged**
