### PR TITLE
Move non entity related stuff to RestfulBase.

### PR DESCRIPTION
**Pull request by e0ipso**
Issue #132

With this PR code is better structured and it opens the door to non-entity based endpoints (manual queries, views, …).

All that is not directly related to an entity has been moved to the `RestfulBase` class.

@amitaibu it should be pretty easy to review since I only did cut & paste and fixed the coupling with the render cache (and its tests).

### CODE REVIEW

**Comment by amitaibu** [comment]
Cool, I'll wait for tests to pass.

btw, @mateu-aguilo-bosch I've granted you commit access to https://www.drupal.org/project/restful, which I maintain as a mirror for make files.

**Comment by e0ipso** [comment]
@amitaibu super. How's the replication handled for the d.o module?

**Comment by amitaibu** [comment]
A manual `git push drupal 7.x-1.x` ;)

**Comment by e0ipso** [comment]
@amitaibu off topic. I ripped part of the restful module (it's a total clone) to create https://github.com/mateu-aguilo-bosch/data_mapper which I needed for work. The idea is to have a standard way to get info out of entities, which is handy in many situations (not only for restful).

Would it make sense to have restful depend on that data_mapper and not to worry about the entity mapping part? That would seem a good architecture to me, but it may be a bit harder to maintain.

**Comment by amitaibu** [comment]
Asked differently -- maybe data-mapper can wrap RESTful?

**Comment by amitaibu** [comment]
Also for now (+since things are moving rapidly), I think we should  keep RESTful dependt only on CTools and Entity API.

**Comment by e0ipso** [comment]
> I think we should keep RESTful dependt only on CTools and Entity API.

Makes sense.

**Comment by e0ipso** [comment]
@amitaibu tests are green.

**Comment by amitaibu** [comment]
Merged, thanks.

**Pull request closed without merging**
