### PR TITLE
Allow files to be uploaded directly through PUT method. 

### PR DESCRIPTION
**Pull request by mpetrovic**
From #483.

If the Content-Type header is not a known value, we assume it's a direct file upload. The file is copied to a temporary location, made into a Drupal File entity, and then put into the request array to be passed to the handler. At this point, it's up to the handler to move the file into a permanent location or process it.

### CODE REVIEW

**Comment by e0ipso** [comment]
@mpetrovic thank you for contributing! Any idea why tests are failing?

**Comment by mpetrovic** [comment]
@mateu-aguilo-bosch 
The tests are failing because they say they set the Content-Type header to 'application/json' data and then actually sending an HTTP encoded string. They either need to set the header to 'application/x-www-form-encoded' or send actual JSON data.

**Comment by mpetrovic** [comment]
@mateu-aguilo-bosch 
There are still 4 tests failing. They are failing because the $_POST array is empty, even though php://input has data and the Content-Type is 'application/x-form-www-encoded'. I can't think of why this would be though.

**Comment by mpetrovic** [comment]
Closing in favor of a cleaner PR.

**Comment by rbran100** [comment]
New PR #568

**Pull request closed without merging**
