### PR TITLE
Fix: 204 status code for HTTP DELETE method doesn't take effect

### PR DESCRIPTION
**Pull request by xuxucode**
execute:

```
curl -X DELETE -D- http://www.example.com/api/articles/100
```

`200` status code returned, it should be `204`.

### CODE REVIEW

**Comment by lukewertz** [comment]
+1 for this PR. Thanks!

**Comment by e0ipso** [comment]
Please re-roll with the latest code.

**Comment by xuxucode** [comment]
sorry, how to re-roll?

**Comment by e0ipso** [comment]
Just merge the latest code in this branch and re-push. :-)

**Comment by e0ipso** [comment]
This was just merged. Thanks!

**Comment by d-arkfores-t** [comment]
@e0ipso I am having the same issue on 2.x. Does this issue still need porting as the label implies?

**Pull request closed without merging**
