### PR TITLE
Document the discovery options.

### PR DESCRIPTION
**Pull request by e0ipso**

### CODE REVIEW

**Comment by amitaibu** [comment]
@mateu-aguilo-bosch damn, you are on fire!

**Comment by e0ipso** [comment]
Yeah! I've been putting a lot of time into this since I want to get this ready for our Lullabot get together and show our work to my folks.

After the discovery effort is done, the last thing that I want to address (and after that we can probably have a RC1) is DX for contributed projects on top of restful. Namely, how easy is to build on top of this to add UIs, documentation outputs, API testing frameworks, contributed Data Providers, …

**Comment by e0ipso** [comment]
@amitaibu I think this is ready to be merged.

**Comment by amitaibu** [comment]
Merged, thanks.

**Pull request closed without merging**
