### PR TITLE
Allow filtering column for a query with joins

### PR DESCRIPTION
**Pull request by amitaibu**
Since `WHERE` and `ORDER BY` can't use an alias column name, we must pass the explicit one. Tests and examples will follow.

### CODE REVIEW

**Comment by amitaibu** [comment]
@mateu-aguilo-bosch ready for review

**Comment by amitaibu** [comment]
actually I should probably add a node_access tag to the query. One sec...

**Comment by amitaibu** [comment]
ready

**Comment by amitaibu** [comment]
@mateu-aguilo-bosch ^^

**Comment by e0ipso** [comment]
Looks good!

**Comment by e0ipso** [comment]
Shit, this broke the tests.

**Comment by amitaibu** [comment]
Weird, it was green. I'll try to have a look tomorrow.

**Pull request closed without merging**
