### PR TITLE
2.x view entity tests

### PR DESCRIPTION
**Pull request by e0ipso**
Adds more testing.

### CODE REVIEW

**Comment by e0ipso** [comment]
@amitaibu w00t! Green tests!

Now I'm back to #491 to fix hook menu tests.

**Comment by amitaibu** [comment]
Great! Lets get it in, and keep tests green from now on?

**Comment by e0ipso** [comment]
Yeah!

**Comment by e0ipso** [comment]
@amitaibu does this mean that we can merge all of the previous PRs this one builds on top of?

**Comment by amitaibu** [comment]
Oh, I miss looked - I thought it was only the tests changes.

I actually still think we need to discuss the `MiddlewareInterface` idea

‫ב-3 במאי 2015, בשעה 18:22, ‏Mateu Aguiló Bosch notifications@github.com כתב/ה:‬

**Comment by e0ipso** [comment]
> I actually still think we need to discuss the `MiddlewareInterface` idea

I am a bit foggy about this. Care to refresh?

**Comment by amitaibu** [comment]
> Care to refresh?

Sure, sorry :)
1) https://github.com/RESTful-Drupal/restful/pull/481#discussion_r29064275
2) https://github.com/RESTful-Drupal/restful/pull/481#issuecomment-97696248

**Pull request merged**
