### PR TITLE
Fix RestfulDataProviderVariable file docblock

### PR DESCRIPTION
**Pull request by christopher-hopper**
Incorrect class name was used in the docblock for this file.

### CODE REVIEW

**Comment by amitaibu** [comment]
I've kicked Travis, I doubt this PR causes an error :)

**Comment by christopher-hopper** [comment]
@amitaibu 
Can we run Travis CI again because I think that this build timed-out or stalled for some reason. The final output was:

```
No output has been received in the last 10 minutes, this potentially indicates a stalled build or something wrong with the build itself.
```

**Comment by amitaibu** [comment]
sure, running again.

**Comment by amitaibu** [comment]
@christopher-hopper oh, I think I see the problem -- you created the PR against 2.x, but you probably meant 1.x :)

**Comment by e0ipso** [comment]
I'm going to close this issue to unclutter the PR view. Feel free to re-open if you pick up this work again.

Thanks for everything!

**Pull request closed without merging**
