### PR TITLE
[FEATURE] Switch user during RESTful execution

### PR DESCRIPTION
**Pull request by e0ipso**

### CODE REVIEW

**Comment by e0ipso** [comment]
Yay! Back to green.

@amitaibu @jeff-h I'm still a bit uneasy about doing this. I fear some sort of privilege escalation.

Mind giving a review? This should be a port from the 1.x feature.

**Comment by jeff-h** [comment]
This is fantastic! Will try it out as soon as I can, although my head's pretty deep in the client side right now.

**Comment by e0ipso** [comment]
This was merged, if anything arises from your analysis we can address it as a follow up.

**Comment by amitaibu** [comment]
This looks like a direct(ish) port from 1.x -- which is working fine, so for an eyeball review, it looks good.

**Comment by amitaibu** [comment]
I think that on this specific issue, my feeling was "what can possibly go wrong" :wink:

**Comment by e0ipso** [comment]
hahaha. Awesome!

**Pull request closed without merging**
