### PR TITLE
Fix tests

### PR DESCRIPTION
**Pull request by alvar0hurtad0**
Issue https://github.com/RESTful-Drupal/restful/issues/991

### CODE REVIEW

**Comment by alvar0hurtad0** [comment]
@amitaibu this reverting this change makes the tests pass but I've not clear if can have any consequence on the security.

**Comment by amitaibu** [comment]
Which PR/ commit caused this change?

**Comment by alvar0hurtad0** [comment]
It's here:

https://github.com/RESTful-Drupal/restful/commit/7420a347472bfb6d979337a3585cb71599b3ec40

**Comment by amitaibu** [comment]
Thanks.

**Pull request merged**
