### PR TITLE
WIP: Better handle variables

### PR DESCRIPTION
**Pull request by amitaibu**
#196

todo: fix `POST`/ `PATCH` / `PUT` that don't work.

### CODE REVIEW

**Comment by amitaibu** [comment]
@mateu-aguilo-bosch 
Apart of improving a bit the `RestfulDataProviderDbQuery` (e.g. use `drupal_write_record()` for insert/ update); I just realized that a better implementation for variables would be to write `variableDataProvider`, that will use: 

list/ read -- `global $conf`
write -- `variable_set()`
delete -- `variable_del()`

**Comment by e0ipso** [comment]
> I just realized that a better implementation for variables would be to write

Totally agreed. I just wanted to provide an implementation example for the query provider. I chose the wrong table. We should probably do a variables example + a generic table example.

**Comment by e0ipso** [comment]
@amitaibu is there anything blocking this one?

**Comment by amitaibu** [comment]
> is there anything blocking this one?

yeah, my laziness ;)

It's not ready yet --RestfulDataProviderDbQuery should probably use `drupal_write_record` and we should add an example RestfulExampleDataProviderVariables that will `variable_get/set/del`

**Comment by e0ipso** [comment]
This is not blocking RC, though? Right?

**Comment by amitaibu** [comment]
not blocking.

**Comment by amitaibu** [comment]
Hi @rfx1007, if you are looking for fun RESTful issues - this one is about writing and fixing data providers... Fun and joy is guaranteed ;)

**Comment by raphaeltraviss** [comment]
Yes, this does sound fun!  I'm in.

**Comment by amitaibu** [comment]
Awesome! :)

**Comment by raphaeltraviss** [comment]
OK, I've got this up and running: pull request https://github.com/RESTful-Drupal/restful/pull/356

**Comment by e0ipso** [comment]
Closing this in favor of #356.

**Pull request closed without merging**
