### PR TITLE
Discovery: Add special endpoint to get all the resources.

### PR DESCRIPTION
**Pull request by e0ipso**
Broken down to version and sub version. To dig for more information one would need to make an OPTIONS call to the particular resource (with the version options).

This and https://github.com/Gizra/restful/issues/197 are the _basics_ for discovery features that I can see. With this in place I can see a `restful_apiary` contrib module that generates automatic up-to date documentation.

### CODE REVIEW

**Comment by e0ipso** [comment]
This was easier than expected :-)

**Comment by amitaibu** [comment]
Nice. I would take a different approach, and treat the discovery resource like any other resource:
1. Add a RestfulDataProviderCToolsPlugin (which is read-only). btw, we can move all data provider specific options to `data_provider_options` in the `$plugin`
2. Add a resource, with explicit public fields (name, description, and URL IMO are enough), instead of one single callback where we unset stuff
3. Let RESTful declare the menu item, so it's api/v1/discovery  -- and the result is still under the `data` key with `count` and `_links` present

**Comment by e0ipso** [comment]
I like this approach much better!

Please disregard this PR when implementing this.

**Comment by e0ipso** [comment]
I used your approach in the docs for this: https://github.com/Gizra/restful/pull/199

The actual docs: https://github.com/mateu-aguilo-bosch/restful/blob/document-discovery-options/README.md#documenting-your-api

**Comment by amitaibu** [comment]
> Please disregard this PR when implementing this.

No problem, I'll give it a stab.

**Comment by amitaibu** [comment]
Closing in favor of #200

**Pull request closed without merging**
