### PR TITLE
_links URLs are wrong

### PR DESCRIPTION
**Pull request by e0ipso**
`api/articles`

local_d7_dev_api_articles_

### CODE REVIEW

**Comment by amitaibu** [comment]
@mateu-aguilo-bosch ^^ this seems to be related to the `$plugin['menu_item']` change -- would you mind giving it a look?

**Comment by e0ipso** [comment]
We should also check the test coverage for that. I would expect tests to fail for the pagination generation.

**Comment by e0ipso** [comment]
@amitaibu this should be fixed now.

**Comment by amitaibu** [comment]
Merged, thanks.

**Pull request closed without merging**
