### PR TITLE
2.x Remove angular example

### PR DESCRIPTION
**Pull request by e0ipso**
:_(

Sad to see it go, but it needs to happen.

### CODE REVIEW

**Comment by amitaibu** [comment]
I think we can move this to  a `restful_angular_example` repo under RESTful-drupal, no?

**Comment by e0ipso** [comment]
That's a good idea. I don't think there's a need for a d.o project, though. Right?

**Comment by amitaibu** [comment]
yeah, just on github would be enough

**Comment by e0ipso** [comment]
Done. I even maintained the git history.

https://github.com/RESTful-Drupal/restful_angular_example

**Comment by amitaibu** [comment]
:+1:

**Pull request merged**
