### PR TITLE
499: Add Node Reference resource support.

### PR DESCRIPTION
**Pull request by iStryker**

### CODE REVIEW

**Comment by e0ipso** [comment]
@iStryker I don't have any environment to test this. Is this working in the following scenarios:
- [ ] Listing entities with node reference fields.
- [ ] Viewing an entity without a resource key.
- [ ] Viewing an entity with the resource key and `full_view => FALSE`.
- [ ] Viewing an entity with the resource key and embedding the result of the target resource.
- [ ] Posting an entity with the info of the embedded resource to create both entities.

Thanks!

**Comment by iStryker** [comment]
I have used it as a resource for a public field and it works.  I will try to test the other parameters in the next day or so.

**Comment by e0ipso** [comment]
@iStryker any progress on this?

**Comment by iStryker** [comment]
Code is now in production and has no problem.  I will try and test it with
the list you mention this week.

**Comment by e0ipso** [comment]
That is awesome! Thanks for the response. I'll be monitoring this issue to hear from your tests.

**Comment by e0ipso** [comment]
This has been merged.

Thanks for the contribution!

**Pull request closed without merging**
