### PR TITLE
add 'configure' key to restful_token_auth.info

### PR DESCRIPTION
**Pull request by alexweber**

### CODE REVIEW

**Comment by e0ipso** [comment]
Nice to see you in here @alexweber

**Comment by e0ipso** [comment]
Thanks for the contribution!!

**Comment by alexweber** [comment]
@mateu-aguilo-bosch awesome! :)

**Comment by e0ipso** [comment]
@alexweber if you feel like it there are several issues in the issue queue that need some love :stuck_out_tongue:

**Comment by alexweber** [comment]
@mateu-aguilo-bosch I'll do my best! :)

**Pull request merged**
