### PR TITLE
Ref 833, Hotfix for hyphen/dash auth headers issue.

### LINKED ISSUE #833: Critical Bug: Access-Token Header Doesn't Work
Using the latest branch `7.x-2.x`, when sending a request with a header like:

```
Access-Token: 123
```

The access token is not read from the headers.

This is because on line 95 of `vendor/drupal/restful/modules/restful_token_auth/src/Plugin/authentication/TokenAuthentication.php` the condition is incorrect. It is currently:

```
if (empty($input[$key_name]) && $request->getHeaders()->get($key_name)->getValueString()) {
```

And it should be something like:

```
if (empty($input[$key_name]) && empty($request->getHeaders()->get($key_name)->getValueString())) {
```

### PR DESCRIPTION
**Pull request by lukewertz**
Fixes #833

### CODE REVIEW

**Comment by lukewertz** [comment]
This is a fairly urgent issue for me, @e0ipso. Sorry for needing to propose the hotfix.

@josephdpurcell outlines the problem here: https://github.com/RESTful-Drupal/restful/issues/833#issuecomment-175280749

This should address the issue that he is experiencing. The 2.x branch right now won't process any access-token headers!

**Comment by josephdpurcell** [comment]
Suggestion: use `!` instead of `empty`. That should fix the failing test.

**Comment by e0ipso** [comment]
@lukewertz I agree with the comment above. Also, tests are failing. :-(

**Comment by fpalluel** [comment]
Hello,

The patch is failing with PHP 5.4 only, isn't it ?
Since PHP 5.4 is not supported any longer... ;-)

**Comment by e0ipso** [comment]
@Moxide Agreed. Let's not hold this any longer and let's make it into the next release.

**Comment by e0ipso** [comment]
Modified and merged.

**Comment by e0ipso** [comment]
Thanks everyone!

**Pull request closed without merging**
