### PR TITLE
Add cache helpers

### PR DESCRIPTION
**Pull request by e0ipso**
See https://github.com/Gizra/restful/pull/285/files#r21149960

>  we should add a `$handler->clearCache()` (to clear all handler's cache), and `$handler->clearCacheByResource($entity)`?

### CODE REVIEW

**Comment by e0ipso** [comment]
This PR depends on #301.

**Comment by amitaibu** [comment]
Needs a re-roll

**Comment by e0ipso** [comment]
> Needs a re-roll

Resolved.

**Comment by amitaibu** [comment]
Merged, thanks.

**Pull request closed without merging**
