### PR TITLE
Cache invalidation for entities broken with request params.

### PR DESCRIPTION
**Pull request by e0ipso**
When the cache ID structure changed in a previous PR, it made it impossible to clear caches on entity updates and deletes for that particular entity.

We also need to add a test for this.
### We have

Cache id without params: `v1.1::uu2::paet:node::ei:1`
Cache id with params: `v1.1::uu2::pafi:id,label::et:node::ei:1`
### We need

Cache id without params: `v1.1::articles::uu2::paet:node::ei:1`
Cache id with params: `v1.1::articles::uu2::paet:node::ei:1::fi:id,label`

### CODE REVIEW

**Comment by e0ipso** [comment]
This is ready to review.

It depends on #297.

**Comment by amitaibu** [comment]
Needs a re-roll

**Comment by e0ipso** [comment]
Conflicts resolved.

**Comment by amitaibu** [comment]
Seems to be merged with #289

**Pull request closed without merging**
