### PR TITLE
Remove recommendation to use HAL+JSON be default

### PR DESCRIPTION
**Pull request by amitaibu**
I don't think it's really recommended, I personally find the simple JSON to be much better for _real life_ use cases.

### CODE REVIEW

**Comment by amitaibu** [comment]
ready for review

**Comment by e0ipso** [comment]
I'm not sure how I feel about recommending the proprietary SimpleJSON over the standard HAL+JSON.

I am not sure how _real life_ use cases apply in this particular case. Meaning that it's just an output format, so choosing one or the other will, probably, be based on preferences. My only argument is standard vs proprietary.

That being said, since this is a matter of _preference_ I am more than glad to let you take your preference.

**Comment by e0ipso** [comment]
Merge at will.

**Comment by amitaibu** [comment]
Since not you nor me are really using the HAL, I think it's ok not to request "newbies" to do it :)

**Pull request merged**
