### PR TITLE
Fix handling of 404 errors

### PR DESCRIPTION
**Pull request by amitaibu**
#207

### CODE REVIEW

**Comment by amitaibu** [comment]
I think [this](https://github.com/Gizra/restful/pull/209/files#diff-2dd0d416dd78166fa5d35d3ac72a6878R771) code is never tested, we should probably add a test as a follow up.

**Comment by amitaibu** [comment]
> I think this code is never tested, we should probably add a test as a follow up.

Sorry, we actually do check this in `\RestfulViewEntityTestCase::testHeaders`.

**Comment by amitaibu** [comment]
@mateu-aguilo-bosch ready for review.

**Comment by e0ipso** [comment]
Cool! This is almost the same I had in https://github.com/Gizra/restful/pull/200/files#diff-2dd0d416dd78166fa5d35d3ac72a6878L754 but better.

**Comment by e0ipso** [comment]
Merged!

Thanks.

**Pull request closed without merging**
