### PR TITLE
Fixing #658

### PR DESCRIPTION
**Pull request by samingle**

### CODE REVIEW

**Comment by e0ipso** [comment]
Good! I had to fix this for `2.x`.

We are not using `!== null` anywhere else in the codebase. Can you change it to `isset` for consistency?

**Comment by samingle** [comment]
Done

**Comment by e0ipso** [comment]
This is ready to be merged.

**Comment by amitaibu** [comment]
I think this calls for a simpleTest to prevent this feature from being lost in the future. @samingle any chance you can provide such a test? :)

**Comment by e0ipso** [comment]
This has been merged in 11e213be925456952de536f0ee5c238738be6c43. Thanks a lot for your contribution!

Please, add any simple tests in a follow up PR.

**Pull request closed without merging**
