### PR TITLE
Use the resource path

### PR DESCRIPTION
**Pull request by e0ipso**
@amitaibu the request path contains `v1.0/resource-name`, so we need to use the resource path to check that it's a listing.

I added a follow up to add testing for this case.

### CODE REVIEW

**Comment by amitaibu** [comment]
I'd expect `$this->request->getPath()` to return the path without the versioning. So result from `getPath()` would be the same if version passed via URL or header.

**Comment by amitaibu** [comment]
Also, you might have custom menu which doesn't correlate with the resource name.

**Comment by e0ipso** [comment]
I tried that approach and found several problems:
1. The `Request` object should not know about the URL templates for the resources.
2. That would only work if we did not allow having custom URLs for the resources (see `'api/login'`).
3. Having the _path inside of a resource_ (like `/1234` for the articles resource) only makes sense in the context of a resource object, not the global `Request`.

That's why there is a separation between the request path and the resource path. Also, that is why we do `$handler->setPath('1234')` in the tests.

**Comment by amitaibu** [comment]
ok, I thought the request path will change based on URL/ header of the versioning.

Test is failing, but seems legit :)

**Comment by e0ipso** [comment]
It turns out we had a couple of broken tests that were firing a false positive :-/

Fixed now :-)

**Comment by e0ipso** [comment]
@amitaibu this is ready for re-review.

**Comment by e0ipso** [comment]
Merged. Added postmortem review tag.

**Pull request closed without merging**
