### PR TITLE
2.x Resource manager

### PR DESCRIPTION
**Pull request by e0ipso**
~~Depends on #398.~~

### CODE REVIEW

**Comment by e0ipso** [comment]
@amitaibu you can see that we are moving in the right direction because we are moving stuff from `RestfulBase` into the appropriate subsystems.

I feel that I cannot avoid porting the resource plugins much longer… But there are several things first that can be done:
- Namespace the exceptions.
- Create the response object.
- …

**Comment by amitaibu** [comment]
> I feel that I cannot avoid porting the resource plugins much longer

What is holding you? apart of the crazy amount of work ;)

**Comment by e0ipso** [comment]
> apart of the crazy amount of work

_Just_ that.

**Comment by amitaibu** [comment]
> Just that.

No worries you won't have to do it alone :)

**Pull request merged**
