### PR TITLE
fix: Add case setter with sub property.

### PR DESCRIPTION
**Pull request by ceoaliongroo**
#171

### CODE REVIEW

**Comment by e0ipso** [comment]
Awesome @ceoaliongroo, thanks for contributing.

Apparently tests came back red though.

**Comment by amitaibu** [comment]
I'm not sure that's the right approach. As for the address field use case, you can 

``` php
$public_fields['address'] = array(
  'property' => 'field_address',
);
```

And then in the request pass it the whole array.

``` php
$request['address'] = array(
  'region' => '...',
  'country' => '...',
);
```

btw, make sure to set your IDE to 2 spaces instead of tabs.

**Comment by e0ipso** [comment]
@ceoaliongroo thanks for taking the time to contribute! As @amitaibu suggests partial updates are only supported at field level. That means that you can send a `PATCH` request and only send the fields that you want to update.

What you **cannot** do is have partial updates within a field (if that was supported then it would be impossible to fit all the custom field implementations that exist).

**Comment by e0ipso** [comment]
@ceoaliongroo I am going to close this for now, please feel free to reopen if you think that RESTful should support this.

**Comment by ceoaliongroo** [comment]
Great!

**Pull request closed without merging**
