### PR TITLE
2264079 is no longer needed to patch

### PR DESCRIPTION
**Pull request by joshuataylor**
As it is now merged with Entity API, remove it from the readme.

### CODE REVIEW

**Comment by e0ipso** [comment]
We also need to remove it from `.travis.yml`.

**Comment by e0ipso** [comment]
Assuming that the patch is in the latest stable release…

**Comment by joshuataylor** [comment]
Ahh bugger, it's not in stable, I was using dev. Will need to wait until a stable release is out.

**Comment by e0ipso** [comment]
I'm closing this for now.

**Pull request closed without merging**
