### PR TITLE
2.x Decorated resources.

### PR DESCRIPTION
**Pull request by e0ipso**
@amitaibu this PR will focus on creating the decorated resources. These will act as a regular resource, but they're are a fairly dumb shell/wrapper around a regular resource. This wrapper will add a small piece of functionality:
- Authentication.
- Rate Limits.
- Cache.

This means that any resource that we implement can get all the features for free.

A special word about cached resources. The caching functionality belongs to the data provider, since it will skip or not the data loading. All you need to do to have your data provider to allow caching is implement `getContext`. That will return a keyed array that will be used to build the _weird_ cache id for smarter cache invalidation. Finally, the caching feature is bubbled up to the `Resource` layer.

All these objects will –not implemented yet– be instantiated (or not) based on the plugin configuration. If there is presence of `rateLimit`, then instead of returning the newly created `$resource`, return `new RateLimitedResource($resource)` (which is a valid `ResourceInterface`).

### CODE REVIEW

**Comment by amitaibu** [comment]
Haven't forgotten about this - I'm going over it..

**Comment by e0ipso** [comment]
@amitaibu awesome. Thanks!

**Comment by amitaibu** [comment]
Ok, lets get this in :)

**Comment by e0ipso** [comment]
Hopefully this is going to start to make sense in no time soon.

[image: http://]
Mateu Aguiló Bosch
[image: http://]about.me/e0ipso
http://about.me/e0ipso

**Pull request merged**
