### PR TITLE
Plugify CSRF token

### PR DESCRIPTION
**Pull request by amitaibu**
#170

### CODE REVIEW

**Comment by amitaibu** [comment]
@mateu-aguilo-bosch before I fix the tests -- does the approach makes sense to you?

**Comment by amitaibu** [comment]
@mateu-aguilo-bosch my PHPstorm debugging fails me here, any chance you can have a quick look, to see why the call to the `api/session/token` fails

**Comment by e0ipso** [comment]
@amitaibu tests are green. I'm going to merge.

**Comment by e0ipso** [comment]
Closed by e59d33a967c8de13b654a425c7fccccc4f3f6c8b

**Comment by amitaibu** [comment]
Thanks!!

**Pull request closed without merging**
