### PR TITLE
Define menu item as MENU_CALLBACK to avoid menu item in navigation

### PR DESCRIPTION
**Pull request by shushu**
#102

@amitaibu had to fork since I failed to push.

### CODE REVIEW

**Comment by amitaibu** [comment]
Thanks. There are other hook_menu() items, can you cover them as-well.

**Comment by shushu** [comment]
@amitaibu I think all covered.

**Comment by amitaibu** [comment]
I'm think there are still a few links.

site-install

**Comment by shushu** [comment]
Did you re-install ?
From my experience clearing cache did not remove existing menu items.

**Comment by amitaibu** [comment]
Merged, thanks.

**Pull request closed without merging**
