### PR TITLE
WIP: Don't register flood event for base auth, if no attempt has been made.

### PR DESCRIPTION
**Pull request by amitaibu**
#327

### CODE REVIEW

**Comment by amitaibu** [comment]
Next is adding a test

**Comment by amitaibu** [comment]
Seems the PR is wrong as we already check this in `\RestfulAuthenticationBasic::applies`

I'll need to try and reproduce on the existing installation why it happened. Maybe the server somehow populated `$_SERVER['PHP_AUTH_USER']` and `$_SERVER['PHP_AUTH_PW']`

**Comment by amitaibu** [comment]
Turns out the "problem" was `.htaccess` password. Once that is set, it indeed populates `$_SERVER['PHP_AUTH_USER']` and `$_SERVER['PHP_AUTH_PW']`

@mateu-aguilo-bosch maybe worth adding a word about it in the docs?

**Comment by e0ipso** [comment]
@amitaibu yeah, I agree. This is going to be a typical thing.

**Pull request closed without merging**
