### PR TITLE
WIP: Unify error response handling in formatter

### PR DESCRIPTION
**Pull request by amitaibu**

### CODE REVIEW

**Comment by amitaibu** [comment]
I guess it's time I created a PR for 2.x and not just review ;)

**Comment by e0ipso** [comment]
Tests are failing, but I don't see why

**Comment by amitaibu** [comment]
Yeah, _seems_ unrelated to the PR. I'll try to kick travis.

**Comment by amitaibu** [comment]
The travis errors are not related to this PR. I'm able to reproduce on 2.x with multiple clear caches:

`
Fatal error: Call to a member function getPluginDefinition() on a non-object in /../restful/modules/restful_token_auth/restful_token_auth.module on line 40
`

**Comment by e0ipso** [comment]
That problem has been there for a long time. It should not cause tests to
be red.

**Comment by amitaibu** [comment]
I'll try to merge #629 to see if it solves the problem.

**Pull request closed without merging**
