### PR TITLE
[FEATURE] All resource menuItem default to api/

### PR DESCRIPTION
**Pull request by e0ipso**
Make all the paths created from the resource to be nested under the
API's path prefix.

### CODE REVIEW

**Comment by e0ipso** [comment]
This changes a bit from `1.x`.

**menuItem:** Determines the URL where the resource is going to live. All paths specified using this definition property will be nested under the API's prefix. Ex: using `menuItem: "my-resource"` will result in `https://example.org/api/my-resource`.

**Comment by amitaibu** [comment]
so this means that `file-upload` which is binary and non-restful will be under `/api` as-well?

**Comment by e0ipso** [comment]
> so this means that file-upload which is binary and non-restful will be under /api as-well?

Yes. Actually, `file-upload` was already under `/api/`.

If we don't want that, we can modify this via regular `hook_menu_alter`.

**Comment by e0ipso** [comment]
See: https://github.com/RESTful-Drupal/restful/pull/700/files#diff-269d980f2e7442e85e3c457c40cece2bL49

**Comment by amitaibu** [comment]
Ok :)
Ready for review?

**Comment by e0ipso** [comment]
Yes!

**Pull request merged**
