### PR TITLE
Fix 'resource' for reference fields to other entities

### PR DESCRIPTION
**Pull request by amitaibu**
#233

Next is adding tests to prevent regression.

### CODE REVIEW

**Comment by amitaibu** [comment]
It seems we are [already](https://github.com/Gizra/restful/blob/7.x-1.x/tests/RestfulViewEntityTestCase.test#L104-L119) testing the reference fields, and somehow it passes - so I'll need to fix also the wrong(?) test.

**Comment by amitaibu** [comment]
Ok, the error seems to happen when the reference is to another resource. Currently the test has a reference field that references same resource as the parent.

**Comment by amitaibu** [comment]
@mateu-aguilo-bosch @mirzu ready for review.

**Comment by mirzu** [comment]
I did a functional test and it works. I don't have anything to add in regards to the code. :+1:

**Comment by e0ipso** [comment]
Merged in https://github.com/Gizra/restful/commit/627cf6f834478f5fc564096662e72c457cdc2f23!

Thanks!

**Pull request closed without merging**
