### PR TITLE
2.x Formatter transformer write operations JSON API

### PR DESCRIPTION
**Pull request by e0ipso**
This PR introduces the formatter bodyParser for JSON API with a test.

To implement a bodyParser you have to take whatever input the formatter takes, and return the same structure that _Simple JSON_ expects.

There is also some refactoring in the `preprocess` method for the `ResourceFieldEntityReference` field to simplify it.

Finally, the documentation was updated with the new format of the input for Simple JSON.

### CODE REVIEW

**Comment by amitaibu** [comment]
How are you doing it so fast?! ;)

**Comment by e0ipso** [comment]
> How are you doing it so fast?! ;)

This is the last oustanding feature I want in before 2.x stabilizes. When that happens I'll REST.

**Comment by e0ipso** [comment]
selfie-0

**Comment by amitaibu** [comment]
That's pretty scary ;)

**Comment by e0ipso** [comment]
> That's pretty scary ;)

It's halloween dude.

**Comment by e0ipso** [comment]
Tests are green. Merging.

**Pull request merged**
