### PR TITLE
Improve filtering by adding some missing operators

### PR DESCRIPTION
**Pull request by ordavidil**
Some of the [field condition operators](https://api.drupal.org/api/drupal/includes%21entity.inc/function/EntityFieldQuery%3A%3AaddFieldCondition/7) like `CONTAINS`, `NOT IN` and `STARTS_WITH` are missing
and they should be allowed to use.

### CODE REVIEW

**Comment by e0ipso** [comment]
@ordavidil thanks for the effort!

Would you mind joining https://github.com/RESTful-Drupal/restful/pull/464 and resolve the merge conflicts there?

I'm closing this as a duplicate, but feel free to reopen.

**Comment by ordavidil** [comment]
@mateu-aguilo-bosch I've been trying to join @edhollinghurst but as [it seems](https://github.com/edhollinghurst/restful/pull/1) there is no reply.

Can you reopen this please?  or should I create a new PR?
Thanks.

**Comment by edhollinghurst** [comment]
Thanks @ordavidil for picking this up. Apologies I haven't had time to look back at the issue.

**Comment by ordavidil** [comment]
@amitaibu 
Ready for review.

**Comment by amitaibu** [comment]
Looking good. Seems the PR is changing the chmod of two files - it should be `0644`

**Comment by ordavidil** [comment]
I've changed back.

**Comment by amitaibu** [comment]
Merged, thanks.

**Comment by e0ipso** [comment]
This was ported to 7.x-2.x in https://github.com/RESTful-Drupal/restful/pull/728. Removing tag.

**Pull request closed without merging**
