### PR TITLE
Improve "users" resource access

### PR DESCRIPTION
**Pull request by amitaibu**
This includes tests for the `/api/login` endpoint.

### CODE REVIEW

**Comment by amitaibu** [comment]
ready for review.

**Comment by amitaibu** [comment]
@mateu-aguilo-bosch are you getting notifications for those PRs?

**Comment by e0ipso** [comment]
For some reason I am not. Isn't it enough to watch the repo?

**Comment by amitaibu** [comment]
Since this PR fixes the users resource + comes with tests I'm going to go ahead an commit it. Any additional fixes required could be done in a follow up.

**Pull request closed without merging**
