### PR TITLE
Fix missing entities returning HTTP 500 instead of a 4XX.

### PR DESCRIPTION
**Pull request by deviantintegral**
This fixes missing entity GETs returning a 500, because the exception class wasn't extending RestfulException. I wasn't totally sure where to put the test, but this seemed like a good start.

### CODE REVIEW

**Comment by amitaibu** [comment]
Hi @deviantintegral !

Thanks for the PR. I think a better place for would be [here](https://github.com/RESTful-Drupal/restful/blob/7.x-1.x/tests/RestfulExceptionHandleTestCase.test)

**Comment by e0ipso** [comment]
After merging https://github.com/deviantintegral/restful/pull/1 this can be merged.

**Comment by deviantintegral** [comment]
Thanks @mateu-aguilo-bosch !

**Comment by amitaibu** [comment]
Merged, thanks!

**Pull request closed without merging**
