### PR TITLE
Admin UI for the access token module.

### PR DESCRIPTION
**Pull request by e0ipso**
Follows from https://github.com/Gizra/restful/pull/264.

Create a new tab with the configurations for the access token module.

### CODE REVIEW

**Comment by e0ipso** [comment]
restful restful 2014-11-24 09-50-51

**Comment by e0ipso** [comment]
restful restful 2014-11-24 09-58-04

**Comment by amitaibu** [comment]
@mateu-aguilo-bosch looks good, but needs a re-roll

**Comment by e0ipso** [comment]
Merged.

**Pull request closed without merging**
