### PR TITLE
Don't throw exception when request contains fields with NULL

### PR DESCRIPTION
**Pull request by jeff-h**
At present the code throws `RestfulBadRequestException` if any of the request fields contain NULL. NULL should be a legitimate field value unless validation says otherwise.

This change fixes that, and also renames the variable `$original_request` to `$unprocessed_fields` which I felt better described its purpose.

### CODE REVIEW

**Comment by jeff-h** [comment]
Also, I'm thinking the tests should include some NULL-handling tests, but I'm unsure how to do that.

**Comment by jeff-h** [comment]
I'm assuming the tests have failed for some other reason. My PR wasn't _that_ dangerous :D

**Comment by e0ipso** [comment]
It would be better to use `array_key_exists`. Also, some tests will need to be adapted to the new behavior.

I agree that `NULL` should be a valid _existing_ value.

**Comment by e0ipso** [comment]
Also, there are merge conflicts in this branch

**Comment by amitaibu** [comment]
Didn't #673 fix this?

**Comment by jeff-h** [comment]
@amitaibu — yeah, #673 has fixed this.

**Pull request closed without merging**
