### PR TITLE
2.x Hook menu & List entity tests

### PR DESCRIPTION
**Pull request by e0ipso**
This will comment out all tests and will bring back tests for hook menu.

From now on tests should be green to merge PRs.

Next is bringing back more tests.

This PR depends on all of the others (including #498) to be merged.

### CODE REVIEW

**Comment by amitaibu** [comment]
> From now on tests should be green to merge PRs.

I think that would be great. It would allow me to jump in and give a hand :)

**Comment by amitaibu** [comment]
Needs a re-roll?

**Comment by e0ipso** [comment]
List entity tests fixed. Yay!

**Comment by e0ipso** [comment]
OMG it took a lot of sweat to get this green. Travis CI was giving me a hard time.

I'm going to merge this before it gets red again.

**Comment by amitaibu** [comment]
:+1:

**Pull request merged**
