### PR TITLE
Cache id performance

### PR DESCRIPTION
**Pull request by e0ipso**

### CODE REVIEW

**Comment by e0ipso** [comment]
Not sure if all these static caches will make using the Drupal API useless. Many of them assume one call per request and have to be cleared manually.

Maybe we should detect if the call is made using the internal API by checking `$request['__application']['rest']` and clear the statics so we don't have to do it manually.

**Comment by amitaibu** [comment]
How much do we gain from those improvements?

**Comment by e0ipso** [comment]
I haven't done any measures but this showed up in my profiling. We're short circuiting `getVersion`, `getAccount` and several string manipulation calls.

**Comment by amitaibu** [comment]
> Maybe we should detect if the call is made

You can invalidate_cache in `process()` - which is the entry point for all calls.

**Comment by e0ipso** [comment]
Anyways, that'll be a new pr. This one can be merged

**Comment by amitaibu** [comment]
Merged, thanks.

**Pull request closed without merging**
