### PR TITLE
Add documentation for filtering via API/URL.

### PR DESCRIPTION
**Pull request by e0ipso**
Forgive me if I am missing it, but I don't see any documentation for how to filter entities when making an API request via URL. It would be greatly beneficial to add this to the README.

https://github.com/Gizra/restful#api-via-url

### CODE REVIEW

**Comment by e0ipso** [comment]
Thanks for contributing. You can see the committed changes in https://github.com/Gizra/restful#filtering-fields-1

**Comment by markdorison** [comment]
@mateu-aguilo-bosch This is super helpful as well but I was actually referring to filtering a list similar to: https://github.com/Gizra/restful#filter

Is this possible via URL?

**Comment by e0ipso** [comment]
That is probably a useful bit of information. It is something like:

``` shell
curl https://example.com/api/v1/articles/1?filter[label]=abc
```

Would you mind writing a pull request?

**Comment by e0ipso** [comment]
Thanks @markdorison!

**Pull request closed without merging**
