### PR TITLE
[FEATURE] Add proper support for operators in EFQ

### PR DESCRIPTION
**Pull request by e0ipso**
When a field is not present and there is a field condition on it then
the entity is excluded from the possible results. This PR will fix
this for the following operators: NOT IN, IS NOT NULL, <>, NOT
BETWEEN, …

### CODE REVIEW

**Comment by e0ipso** [comment]
This PR depends on: #639 and #636.

**Comment by e0ipso** [comment]
Given the following scenario:

```
GET /api/v1.0/videos?include=image,show&fields=tags&filter[uuid]=3e696db3-bb24-4c2c-8503-eba312305888

{
    "data": [
        {
            "type": "videos",
            "id": "3e696db3-bb24-4c2c-8503-eba312305888",
            "attributes": {
                "tags": null
            }
        }
    ],
    "meta": {
        "count": 1
    },
    "links": {
        "self": "http://restful.local/api/v1.0/videos"
    }
}
```

Where the video does not have `field_tags` populated.

## Before the PR

#### Request

```
GET /api/v1.0/videos?include=image,show&fields=tags&filter[uuid]=3e696db3-bb24-4c2c-8503-eba312305888&filter[tags][value]=2009&filter[tags][operator]=NOT%20IN

{
    "data": [],
    "meta": {
        "count": 0
    },
    "links": {
        "self": "http://restful.local/api/v1.0/videos"
    }
}
```

#### Query:

``` sql
SELECT DISTINCT field_data_field_tags0.entity_type AS entity_type, field_data_field_tags0.entity_id AS entity_id, field_data_field_tags0.revision_id AS revision_id, field_data_field_tags0.bundle AS bundle
FROM 
field_data_field_tags field_data_field_tags0
INNER JOIN file_managed file_managed ON file_managed.fid = field_data_field_tags0.entity_id
WHERE 
  (field_data_field_tags0.field_tags_tid NOT IN  ('2009')) AND
  (field_data_field_tags0.deleted = '0') AND
  (file_managed.filemime = 'video/mpx') AND
  (file_managed.published = '1') AND
  (file_managed.status = '1') AND
  (file_managed.uuid = '3e696db3-bb24-4c2c-8503-eba312305888') AND
  (field_data_field_tags0.entity_type = 'file') 
LIMIT 50 OFFSET 0;
```

## After the PR

#### Request

```
GET /api/v1.0/videos?include=image,show&fields=tags&filter[uuid]=3e696db3-bb24-4c2c-8503-eba312305888&filter[tags][value]=2009&filter[tags][operator]=NOT%20IN

{
    "data": [
        {
            "type": "videos",
            "id": "3e696db3-bb24-4c2c-8503-eba312305888",
            "attributes": {
                "tags": null
            }
        }
    ],
    "meta": {
        "count": 1
    },
    "links": {
        "self": "http://restful.local/api/v1.0/videos"
    }
}
```

#### Query:

``` sql
SELECT DISTINCT file_managed.fid AS entity_id, file_managed.vid AS revision_id, file_managed.type AS bundle, 'file' AS entity_type
FROM 
file_managed file_managed
LEFT JOIN field_data_field_tags field_data_field_tags0 ON file_managed.fid = field_data_field_tags0.entity_id
WHERE
    (file_managed.filemime = 'video/mpx') AND
    (file_managed.published = '1') AND
    (file_managed.status = '1') AND
    (file_managed.uuid = '3e696db3-bb24-4c2c-8503-eba312305888') AND
    (
        (field_data_field_tags0.field_tags_tid NOT IN  ('2009')) OR
        (field_data_field_tags0.field_tags_tid IS NULL )
    ) AND
    (
        (field_data_field_tags0.deleted = '0') OR
        (field_data_field_tags0.deleted IS NULL )
    ) AND
    (
        (field_data_field_tags0.entity_type = 'file') OR
        (field_data_field_tags0.entity_type IS NULL )
    )
LIMIT 50 OFFSET 0;
```

I know that the diff is going to be very hard to review, I apologize in advance.

**Comment by e0ipso** [comment]
Tests are green now

**Comment by amitaibu** [comment]
@e0ipso I'm on the fence with this one, since in fact you are trying to fix EFQ, but only inside RESTful. While I agree that the fix could be needed, it is adding a lot of risky code. I'm saying risky because with my own attempts with OG to rebuild the query, I've realized there are plenty of edge cases - which could also be added with `hook_query_TAG_alter()`.

Admittedly, I couldn't even do a proper review due to the complexity. Maybe we can get this in, but there's a chance we'll need to re-address it.

**Comment by e0ipso** [comment]
I see your points. The only thing is that since you are dealing with non-Drupal frontenders, you cannot tell them `Hey! This is how Drupal works!`, because they don't give a :hankey: They just want their backend to work appropriately.

We need the custom EFQ class for the nested filters (killer feature IMO). So we can go a bit further and add this as well. If we see many issues popping up, we can deprecate support later on.

Thoughts?

**Comment by amitaibu** [comment]
Ok, go ahead an merge. Lets dazzle everybody with this feature in Barcelona :sparkles:

**Comment by e0ipso** [comment]
merged

**Pull request closed without merging**
